// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUuifVteGUnjFuI9o7yLXA_Mj1Jq4vuOQ',
    appId: '1:805060795899:web:3694a316c86cf2d1717f5e',
    messagingSenderId: '805060795899',
    projectId: 'airbnb-app-d35b5',
    authDomain: 'airbnb-app-d35b5.firebaseapp.com',
    storageBucket: 'airbnb-app-d35b5.firebasestorage.app',
    measurementId: 'G-80M93V5LT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Bii-2qoCs4AjqCiORNRgpruUgd-fYNA',
    appId: '1:805060795899:android:5d6a5ecee69d5066717f5e',
    messagingSenderId: '805060795899',
    projectId: 'airbnb-app-d35b5',
    storageBucket: 'airbnb-app-d35b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiiaXfag5uCP5HMXR7gWnwXn142w453bw',
    appId: '1:805060795899:ios:8e8a75a51f6afc7d717f5e',
    messagingSenderId: '805060795899',
    projectId: 'airbnb-app-d35b5',
    storageBucket: 'airbnb-app-d35b5.firebasestorage.app',
    iosBundleId: 'com.example.airbnbApp',
  );
}
